---

- name: Demo app vhost
  become_user: root
  template: >
    src=vhosts/demo-app.conf.j2
    dest=/etc/nginx/conf.d/demo-app.conf

- name: Restart nginx
  become_user: root
  service: name=nginx state=restarted
