services:
    demo.behat.context.domain.api:
        class: Demo\Behat\Context\Domain\ApiContext
        arguments:
            - "@__symfony__.router"
            - "@__symfony__.doctrine"
            - "@__symfony__.kernel"
            - "@demo.behat.service.shared_storage"
        tags:
            - { name: "fob.context_service" }

    demo.behat.context.domain.json:
        class: Demo\Behat\Context\Domain\JsonContext
        arguments:
            - "@demo.behat.service.shared_storage"
        tags:
            - { name: "fob.context_service" }
